counter css
isdi-coders-202207-bcn-coding-adventure/pablo-sobrino-front pull request #3
Opened 2022-08-22 14:50 UTC by PabloSob

2022-08-22 14:54 UTC, luisdudamel commented on src/components/Counter/CounterStyled.ts
> +  & .counter__name {
Hola Pablo,
En styled components, aprovechemos el nesteo de selectores.
No repetimos varias veces un mismo selector que comienza igual.

2022-08-22 14:57 UTC, PabloSob commented on src/components/Counter/CounterStyled.ts
> +  & .counter__name {
Cierto, corregido!

2022-08-22 15:08 UTC, PabloSob commented on src/components/Counter/CounterStyled.ts
> +  & .counter__name {
Ahora si, me he enterado

2022-08-23 07:03 UTC, luisdudamel requested changes

2022-08-23 07:03 UTC, luisdudamel commented on src/components/Counter/CounterStyled.ts
> +  & li {
Hola Pablo.
El símbolo de ampersand, es para concatenar selectores, en este caso no estás concatenando ningún selector.

2022-08-23 10:55 UTC, PabloSob commented on src/components/Counter/CounterStyled.ts
> +  & li {
corregido y pusheado

2022-08-23 10:58 UTC, mariogl approved these changes
Fase 4: Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-23 11:09 UTC, luisdudamel approved these changes

2022-08-23 11:09 UTC, merged